# Build releases and (on tags) publish to PyPI
name: Release

on:
  push:
  pull_request:

jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Configura o Python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Instala dependências usando requirements.txt
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip freeze

      # Constrói os pacotes para distribuição
      - name: Build release
        run: |
          pip install build
          python -m build --sdist --wheel .
          ls -l dist

      # Publica no PyPI (somente em tags)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          
